swagger-api:
  version: "1.0"

spring:
  liquibase:
    enabled: true
  jpa:
    properties:
      hibernate:
        default_schema: ulab_edu
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userbook
    username: ROOT
    password: 112003
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

server:
  port: 8091
  servlet:
    context-path: /app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info